In [ ]:
import numpy as np

class QuantumSimulator:
    def __init__(self):
        # A standard qubit starts in the |0> state.
        # Represented as a 2D column vector: [alpha, beta]
        self.state = np.array([[1.0],
                               [0.0]])

    def display_probabilities(self):
        # The probability of measuring 0 or 1 is the square of the absolute value of its amplitude.
        prob_0 = np.abs(self.state[0][0])**2
        prob_1 = np.abs(self.state[1][0])**2

        print(f"Current State Vector:\n{self.state}\n")
        print(f"P(|0>) = {prob_0:.2f}")
        print(f"P(|1>) = {prob_1:.2f}")

# Initialize and test the simulator
sim = QuantumSimulator()
sim.display_probabilities()

Current State Vector:
[[1.]
 [0.]]

P(|0>) = 1.00
P(|1>) = 0.00


In [ ]:
import numpy as np

class QuantumSimulator:
    def __init__(self):
        # A standard qubit starts in the |0> state.
        self.state = np.array([[1.0],
                               [0.0]])

    def apply_x_gate(self):
        # The X gate matrix
        x_matrix = np.array([[0, 1],
                             [1, 0]])
        # Multiply the matrix by the current state vector
        self.state = np.dot(x_matrix, self.state)
        print("\n--- Applied X Gate ---")

    def apply_h_gate(self):
        # The Hadamard gate matrix
        h_matrix = (1 / np.sqrt(2)) * np.array([[1,  1],
                                                [1, -1]])
        self.state = np.dot(h_matrix, self.state)
        print("\n--- Applied H Gate ---")

    def display_probabilities(self):
        prob_0 = np.abs(self.state[0][0])**2
        prob_1 = np.abs(self.state[1][0])**2

        # Rounding for cleaner output
        print(f"Current State Vector:\n{np.round(self.state, 4)}\n")
        print(f"P(|0>) = {prob_0:.2f}")
        print(f"P(|1>) = {prob_1:.2f}")

# 1. Initialize simulator
sim = QuantumSimulator()
print("Initial State:")
sim.display_probabilities()

# 2. Test X Gate
sim.apply_x_gate()
sim.display_probabilities()

# 3. Test H Gate
sim.apply_h_gate()
sim.display_probabilities()

Initial State:
Current State Vector:
[[1.]
 [0.]]

P(|0>) = 1.00
P(|1>) = 0.00

--- Applied X Gate ---
Current State Vector:
[[0.]
 [1.]]

P(|0>) = 0.00
P(|1>) = 1.00

--- Applied H Gate ---
Current State Vector:
[[ 0.7071]
 [-0.7071]]

P(|0>) = 0.50
P(|1>) = 0.50


In [ ]:
import numpy as np

class TwoQubitSimulator:
    def __init__(self):
        # Initialize two individual |0> qubits
        q0 = np.array([[1.0], [0.0]])
        q1 = np.array([[1.0], [0.0]])

        # Combine them into a single 4D state vector using the Kronecker product
        self.state = np.kron(q0, q1)
        print("--- Initial State (|00>) ---")
        self.display_probabilities()

    def apply_h_gate_q0(self):
        # The Hadamard gate matrix
        h_matrix = (1 / np.sqrt(2)) * np.array([[1,  1],
                                                [1, -1]])
        # The Identity matrix (does nothing to q1)
        i_matrix = np.array([[1, 0],
                             [0, 1]])

        # To apply H to q0 and do nothing to q1, we tensor H and I
        h_total = np.kron(h_matrix, i_matrix)

        # Apply the combined 4x4 matrix to our 4D state vector
        self.state = np.dot(h_total, self.state)
        print("\n--- Applied H Gate to Qubit 0 ---")

    def apply_cnot(self):
        # The CNOT gate matrix (q0 is control, q1 is target)
        cnot_matrix = np.array([
            [1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, 0, 1],
            [0, 0, 1, 0]
        ])

        self.state = np.dot(cnot_matrix, self.state)
        print("\n--- Applied CNOT Gate ---")

    def display_probabilities(self):
        # The 4 indices correspond to the states |00>, |01>, |10>, |11>
        states = ['00', '01', '10', '11']

        print(f"Current State Vector:\n{np.round(self.state, 4)}\n")
        for i in range(4):
            prob = np.abs(self.state[i][0])**2
            print(f"P(|{states[i]}>) = {prob:.2f}")

# Execute the Bell State Workflow
sim = TwoQubitSimulator()
sim.apply_h_gate_q0()
sim.apply_cnot()
sim.display_probabilities()

--- Initial State (|00>) ---
Current State Vector:
[[1.]
 [0.]
 [0.]
 [0.]]

P(|00>) = 1.00
P(|01>) = 0.00
P(|10>) = 0.00
P(|11>) = 0.00

--- Applied H Gate to Qubit 0 ---

--- Applied CNOT Gate ---
Current State Vector:
[[0.7071]
 [0.    ]
 [0.    ]
 [0.7071]]

P(|00>) = 0.50
P(|01>) = 0.00
P(|10>) = 0.00
P(|11>) = 0.50


In [ ]:
import time
import sys

# Start tracking
start_time = time.time()

# Execute your circuit here
sim = TwoQubitSimulator()
sim.apply_h_gate_q0()
sim.apply_cnot()

# End tracking
execution_time = time.time() - start_time
# sys.getsizeof() measures the memory footprint of the NumPy array in bytes
memory_usage = sys.getsizeof(sim.state)

print(f"\n--- KPI Metrics ---")
print(f"Execution Time: {execution_time:.6f} seconds")
print(f"Memory Usage: {memory_usage} bytes")
print(f"State Vector Size: {len(sim.state)} elements")

--- Initial State (|00>) ---
Current State Vector:
[[1.]
 [0.]
 [0.]
 [0.]]

P(|00>) = 1.00
P(|01>) = 0.00
P(|10>) = 0.00
P(|11>) = 0.00

--- Applied H Gate to Qubit 0 ---

--- Applied CNOT Gate ---

--- KPI Metrics ---
Execution Time: 0.001426 seconds
Memory Usage: 160 bytes
State Vector Size: 4 elements


KPI DOCUMENTATION

In [ ]:
import time
import sys

# Start tracking
start_time = time.time()

# Execute your circuit here
sim = TwoQubitSimulator()
sim.apply_h_gate_q0()
sim.apply_cnot()

# End tracking
execution_time = time.time() - start_time
# sys.getsizeof() measures the memory footprint of the NumPy array in bytes
memory_usage = sys.getsizeof(sim.state)

print(f"\n--- KPI Metrics ---")
print(f"Execution Time: {execution_time:.6f} seconds")
print(f"Memory Usage: {memory_usage} bytes")
print(f"State Vector Size: {len(sim.state)} elements")

--- Initial State (|00>) ---
Current State Vector:
[[1.]
 [0.]
 [0.]
 [0.]]

P(|00>) = 1.00
P(|01>) = 0.00
P(|10>) = 0.00
P(|11>) = 0.00

--- Applied H Gate to Qubit 0 ---

--- Applied CNOT Gate ---

--- KPI Metrics ---
Execution Time: 0.000899 seconds
Memory Usage: 160 bytes
State Vector Size: 4 elements


# Technical Report: Hybrid Quantum Circuit Simulation

## 1. Implementation Approach and State Representation

The simulation engine models quantum states using linear algebra primitives, establishing a foundation that seamlessly bridges wave mechanics and classical computational modeling. A single qubit is represented as a 2D column vector storing the complex probability amplitudes $\alpha$ and $\beta$, strictly satisfying the normalization condition $\vert{}\alpha\vert{}^2 + \vert{}\beta\vert{}^2 = 1$.

Superposition and entanglement are modeled by projecting the baseline vectors $\vert{}0\rangle$ and $\vert{}1\rangle$ through transformation matrices.

* **Pauli-X (NOT) Gate**: Executed as a matrix multiplication that flips the state vector amplitudes.


* **Hadamard (H) Gate**: Forces a localized probability distribution into an equal superposition, representing fundamental quantum uncertainty.


* **CNOT Gate**: Modeled as a $4 \times 4$ transformation matrix over a 4D state vector (created via Kronecker product).



## 2. Circuit Explanation and KPI Discussion

To evaluate multi-qubit execution, the simulator executes a standard Bell State workflow.

**Execution Workflow:**

1. A Hadamard gate is applied to qubit 0, transforming it into a superposition state.


2. A CNOT gate acts on the unified system, utilizing qubit 0 as the control and qubit 1 as the target.


3. The resulting entangled state yields a probability distribution of exactly 0.50 for $\vert{}00\rangle$ and 0.50 for $\vert{}11\rangle$.



**KPI Evaluation:**
System metrics were captured using standard process timers and memory profiling.

* **Execution Time**: The application of $2 \times 2$ and $4 \times 4$ matrices executes in microseconds, well within acceptable latency bounds for standard CPU processing.
* **State Vector Scaling**: A single-qubit system requires a 2-element vector, while a two-qubit system requires a 4-element vector. The scaling behaves exponentially ($2^n$, where $n$ represents the number of simulated qubits).


* **Memory Footprint**: While classical memory easily stores the 2-qubit footprint, the geometric scaling dictates that simulating systems around 50 qubits will exhaust all available RAM due to the rapid explosion of probability amplitudes.



## 3. Hardware Analysis and FPGA Feasibility

Translating this software model into dedicated silicon requires optimizing the logic for a Field Programmable Gate Array (FPGA) or custom electronic instrumentation. The current CPU-bound simulator is highly inefficient for complex matrix multiplication.

* **Fixed-Point vs. Floating-Point Arithmetic**: The Python simulator natively relies on floating-point operations. Synthesizing full floating-point logic pipelines on an FPGA consumes massive swathes of finite lookup tables and logic gates. Transitioning the arithmetic core to fixed-point numeric representation drastically compresses the logic footprint and accelerates gate throughput, though it introduces slight precision quantization errors in the terminal probability calculations.


* **Matrix Parallelism**: Quantum gate operations map cleanly to parallelized matrix dot products. Standard CPU architecture evaluates these sequentially. A custom VLSI architecture can execute these row-column operations concurrently within a single clock cycle, maximizing hardware throughput.


* **Memory Architectures**: The exponential growth of the state vector creates severe memory bandwidth bottlenecks between the logic fabric and external DDR. Implementing a sparse storage technique—allocating on-chip block RAM only for non-zero amplitudes—directly mitigates bandwidth saturation and enables the physical simulator to support more qubits.



## 4. Failure Analysis and Limitations

The primary failure mode of this software simulator is its inability to scale polynomially. As qubit counts increase, the exponential memory requirement ($2^n$) directly throttles runtime and crashes standard compute nodes. Furthermore, matrix operations on classical CPUs suffer from cache-miss penalties as the state vectors rapidly exceed standard L1/L2 caching boundaries.

For future iterations targeting hardware acceleration, addressing fixed-point rounding errors is critical. While fixed-point math enables practical FPGA porting, the data width must be rigorously calibrated against the necessary fidelity of the quantum simulation to prevent compounding errors from collapsing fragile probability measurements over deep circuits.